---
title: "finalwebdata code"
output: html_document
---

Load Data
```{r}
library(RPostgreSQL)
drv = dbDriver("PostgreSQL")
samplecon <- dbConnect(drv,
host = "db.panoply.io",
port = "XXXX",
user = "XXXXXXXXXXXX@axosbank.com",
password = "XXXXXXX",
dbname = "XXXXXXXXXXXX")
sampledf = dbReadTable(samplecon, "googleanalytics_cidhitcombined_current")
```



Clean Data
```{r}
library(dplyr)
library(gdata)
library(purrr)
library(data.table)
openaccount = subset(sampledf, grepl( 'enrollment', sampledf$pagepath))
notchillpages = subset(sampledf, !grepl( 'axosbanklo', sampledf$pagepath) & !startsWith(sampledf$pagepath, 'apps', trim=T, ignore.case=T) & !startsWith(sampledf$pagepath, 'app', trim=T, ignore.case=T) & !startsWith(sampledf$pagepath, 'axos', trim=T, ignore.case=T)& !startsWith(sampledf$pagepath, 'careers', trim=T, ignore.case=T)& !startsWith(sampledf$pagepath, 'hello', trim=T, ignore.case=T) & !startsWith(sampledf$pagepath, 'homeloans', trim=T, ignore.case=T) & !startsWith(sampledf$pagepath, 'www', trim=T, ignore.case=T) & !startsWith(sampledf$pagepath, 'nationwide.axos', trim=T, ignore.case=T) & !startsWith(sampledf$pagepath, 'web', trim=T, ignore.case=T))
IDs2Remove = as.data.frame(unique(notchillpages$clientid))
colnames(IDs2Remove) = c('clientid')
temp = openaccount %>%
    group_by(clientid) %>%
    arrange(datehourminute) %>%
    slice(1L)
IDs2Remove = merge(IDs2Remove, temp, by = 'clientid', all.x = T)
IDs2Remove = subset(IDs2Remove, is.na(IDs2Remove$id))
fulldata = subset(sampledf, !(sampledf$clientid %in% IDs2Remove$clientid))
temp$applied = 1
session = left_join(fulldata, temp, by = c("clientid" = "clientid"))
session$datehourminute.y[is.na(session$datehourminute.y)] = Sys.time()
session2 <- session[!(session$datehourminute.y <= session$datehourminute.x),]
notchillpages = subset(session2, !grepl( 'axosbanklo', session2$pagepath.x) & !startsWith(session2$pagepath.x, 'apps', trim=T, ignore.case=T) & !startsWith(session2$pagepath.x, 'app', trim=T, ignore.case=T) & !startsWith(session2$pagepath.x, 'axos', trim=T, ignore.case=T)& !startsWith(session2$pagepath.x, 'careers', trim=T, ignore.case=T)& !startsWith(session2$pagepath.x, 'hello', trim=T, ignore.case=T) & !startsWith(session2$pagepath.x, 'homeloans', trim=T, ignore.case=T) & !startsWith(session2$pagepath.x, 'www', trim=T, ignore.case=T) & !startsWith(session2$pagepath.x, 'nationwide.axos', trim=T, ignore.case=T) & !startsWith(session2$pagepath.x, 'web', trim=T, ignore.case=T))
IDs2Remove = as.data.frame(unique(notchillpages$clientid))
colnames(IDs2Remove) = c('clientid')
session2 = subset(session2, !(session2$clientid %in% IDs2Remove$clientid))
pages = as.data.frame(session2 %>% count(pagepath.x))
uselesspages = pages[!(pages$n >= 20000),]
session <- session2[!(session2$pagepath.x %in% uselesspages$pagepath.x),]
session$value = 1
modeldata1 = as.data.frame(session2 %>% count(clientid, applied))
sourcesraw = cbind.data.frame(session2$clientid, session2$sourcemedium.x)
colnames(sourcesraw) = c("clientid", "sourcemedium.x")
sources = as.data.frame(sourcesraw %>% count(sourcemedium.x))
sourcesraw = cbind.data.frame(session2$clientid, session2$sourcemedium.x)
colnames(sourcesraw) = c("clientid", "sourcemedium.x")
sources = as.data.frame(sourcesraw %>% count(sourcemedium.x))
uselesssources = sources[!(sources$n >= 10000),]
sourcesraw = sourcesraw[!(sourcesraw$sourcemedium.x %in% uselesssources$sourcemedium.x),]
sourcesraw$value = 1
session2$value = 1
modeldata3 = suppressWarnings(dcast(session2, clientid ~ operatingsystem.x, value.var = "value", fun.aggregate = min))
modeldata2 = dcast(session, clientid ~ pagepath.x, value.var = "value", fun.aggregate = min)
modeldata4 = dcast(sourcesraw, clientid ~ sourcemedium.x, value.var = "value", fun.aggregate = min)
modeldata = merge(modeldata1, modeldata2, by = "clientid", all.x = T)
modeldata = merge(modeldata, modeldata3, by = "clientid", all.x = T)
modeldata = merge(modeldata, modeldata4, by = "clientid", all.x = T)
modeldata$applied[is.na(modeldata$applied)] = 0
for (i in 1:ncol(modeldata)) set(modeldata, which(is.infinite(modeldata[[i]])), i, 0)
modeldata[is.na(modeldata)] = 0
colnames(modeldata)[3] = c("pagehits")
```




```{r}
logit2 <- glm(applied ~ . - clientid  -	applied 
              - `apps.axosbank.com/personalloans#/applicant/financialinformation`
              - `apps.axosbank.com/personalloans#/applicant/generalinformation`
              - `www.axosbank.com/personal/cds`
              - `Firefox OS`
              - FreeBSD
              - iOS
              - Linux 
              - Macintosh
              - NetBSD
              - `Nintendo WiiU`
              - Nokia 
              - `OS/2`
              - PalmOS
              - `Nintendo WiiU`
              - Nokia
              - `OS/2`
              - PalmOS
              - `Playstation 3`
              - `Playstation 4` 
              - `Playstation Vita`
              - Samsung   
              - SymbianOS
              - Tizen
              - `Windows Phone`
              - Xbox  
              - `NA`
              - `correspondent.bankofinternet.com / referral`
              - `duckduckgo / organic`
              - `jha.loanspq.com / referral` 
              
, data = modeldata, family = "binomial")
```

```{r}
predictions = modeldata
predictions$`hello.ufbdirect.com/ufb-premium-money-market` = 0
predictions$`www.axosbank.com/personal` = 0
predictions$`nationwide.axosbank.com/personal` = 0
predictions$`www.axosbank.com/personal/checking/compare-checking-accounts` = 0
predictions$`www.axosbank.com/business/open-account-return-to-application` = 0
predictions$`www.axosbank.com/customer-support/personal-support` = 0
predictions$`www.axosbank.com/personal/savings` = 0
predictions$`www.axosbank.com/home` = 0
predictions$`www.axosbank.com/partners` = 0
predictions$`www.axosbank.com/business/small-business-banking` = 0
predictions$`www.axosbank.com/business` = 0
predictions$`www.axosbank.com/` = 0
predictions$`www.axosbank.com/personal/personal-loans` = 0
predictions$`apps.axosbank.com/personalloans#/home` = 0
predictions$`www.axosbank.com/personal/iras` = 0
predictions$`www.axosbank.com/customer-support` = 0
predictions$`apps.axosbank.com/personalloans` = 0
predictions$`google / ppc` = 0
predictions$`nationwide.com / referral` = 0
predictions$`bing / ppc` = 0
predictions$`facebook / paidsocial` = 0
predictions$`bofifederalbank.com / referral` = 0
predictions$`bing / organic` = 0
predictions$`yahoo / organic` = 0
predictions$`google / organic` = 0
predictions$`nationwidesite / weburl` = 0
predictions$`netteller.com / referral` = 0
test = predict(logit2, predictions, type= "response")
predictions$prediction = test
```


```{r}
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer")
fwrite(predictions, "acquisitionpredictions.csv")
```












