---
title: "MWA Testing"
output: html_document
---


#INPUT


###NEWWave


```{r}
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
InputUsers = read.table("Deconv_UserData.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE")
InputAlerts = read.table("Deconv_Alerts.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE")
InputRT = read.table("Deconv_RecurringTransfers.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE")
InputOT = read.table("Deconv_Transfers.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE")
InputAcct = read.table("Deconv_AccountData.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE")
```


```{r}
InputRT = subset(InputRT, InputRT$Status == 'WILLPROCESSON')
InputRT$FirstDueDate = as.Date(InputRT$FirstDueDate, format = "%m/%d/%Y")
InputRT$NextChildToBeSpawned = as.Date(InputRT$NextChildToBeSpawned, format = "%m/%d/%Y")
for(i in 1:length(InputRT$RecurrenceMode)){ if((InputRT$RecurrenceMode[i] == "")&(InputRT$TotalInstances[i] == -1)){InputRT$RecurrenceMode[i] = "ContinueIndefinitely"}}
for(i in 1:length(InputRT$RecurrenceMode)){ if((InputRT$RecurrenceMode[i] == "")){InputRT$RecurrenceMode[i] = "ContinueForXInstances"}}
InputRT$RemainingInstances = InputRT$TotalInstances - (InputRT$ChildrenSpawned + InputRT$SkippedInstances)
for(i in 1:length(InputRT$RecurrenceMode)){ if((InputRT$RecurrenceMode[i] == "ContinueIndefinitely")){InputRT$RemainingInstances[i] = 10000}}
InputRT = InputRT[-c(which(InputRT$Frequency == "TwiceAMonth")),]
InputRT = InputRT[-c(which(InputRT$Frequency == "Bi-Monthly")),]
InputRT$MaxDueDate = as.Date(InputRT$MaxDueDate, format = "%m/%d/%Y")
for(i in 1:length(InputRT$RecurrenceMode)){if((InputRT$RecurrenceMode[i] == "ContinueTillDate")&(InputRT$Frequency[i] == "Weekly")){InputRT$RemainingInstances[i] = difftime(InputRT$MaxDueDate[i],
InputRT$NextChildToBeSpawned[i], units = "weeks")}}
for(i in 1:length(InputRT$RecurrenceMode)){if((InputRT$RecurrenceMode[i] == "ContinueTillDate")&(InputRT$Frequency[i] == "BiWeekly")){InputRT$RemainingInstances[i] = difftime(InputRT$MaxDueDate[i],
InputRT$NextChildToBeSpawned[i], units = "weeks")/2}}
monnb <- function(d) { lt <- as.POSIXlt(as.Date(d, origin="1900-01-01")); 
                          lt$year*12 + lt$mon }
mondf <- function(d1, d2) { monnb(d2) - monnb(d1) }
yrnb <- function(d) { lt <- as.POSIXlt(as.Date(d, origin="1900-01-01")); 
                          lt$year }
yrdf <- function(d1, d2) { yrnb(d2) - yrnb(d1) }
for(i in 1:length(InputRT$RecurrenceMode)){if((InputRT$RecurrenceMode[i] == "ContinueTillDate")&(InputRT$Frequency[i] == "Monthly")){InputRT$RemainingInstances[i] = mondf(InputRT$NextChildToBeSpawned[i], InputRT$MaxDueDate[i]
)}}
for(i in 1:length(InputRT$RecurrenceMode)){if((InputRT$RecurrenceMode[i] == "ContinueTillDate")&(InputRT$Frequency[i] == "Annually")){InputRT$RemainingInstances[i] = yrdf(InputRT$NextChildToBeSpawned[i], InputRT$MaxDueDate[i]
)}}
for(i in 1:length(InputRT$RecurrenceMode)){InputRT$RemainingInstances[i] = trunc(InputRT$RemainingInstances[i])}
for(i in 1:length(InputRT$RecurrenceMode)){if(InputRT$RemainingInstances[i] > 1000){InputRT$RemainingInstances[i] = 150}}
InputRT$RemainingInstances = InputRT$RemainingInstances + 1
InputRTMonthly = subset(InputRT, InputRT$Frequency == "Monthly")
InputRTWeekly = subset(InputRT, InputRT$Frequency == "Weekly")
InputRTBiWeekly = subset(InputRT, InputRT$Frequency == "BiWeekly")
InputRTAnnually = subset(InputRT, InputRT$Frequency == "Annually")
InputRTQuarterly = subset(InputRT, InputRT$Frequency == "Quarterly")
InputRTSemiAnnually = subset(InputRT, InputRT$Frequency == "Semi-Annually")
InputRTMonthly$Dates = apply(InputRTMonthly,1,function(x) { seq.Date( as.Date(x[['NextChildToBeSpawned']], origin="1970-01-01"), by='months', length.out = as.numeric(x['RemainingInstances'])) } )
InputRTWeekly$Dates = apply(InputRTWeekly,1,function(x) { seq.Date( as.Date(x[['NextChildToBeSpawned']], origin="1970-01-01"), by='weeks', length.out = as.numeric(x['RemainingInstances'])) } )
InputRTBiWeekly$Dates = apply(InputRTBiWeekly,1,function(x) { seq.Date( as.Date(x[['NextChildToBeSpawned']], origin="1970-01-01"), by='2 week', length.out = as.numeric(x['RemainingInstances'])) } )
InputRTAnnually$Dates = apply(InputRTAnnually,1,function(x) { seq.Date( as.Date(x[['NextChildToBeSpawned']], origin="1970-01-01"), by='year', length.out = as.numeric(x['RemainingInstances'])) } )
InputRTQuarterly$Dates = apply(InputRTQuarterly,1,function(x) { seq.Date( as.Date(x[['NextChildToBeSpawned']], origin="1970-01-01"), by='quarter', length.out = as.numeric(x['RemainingInstances'])) } )
InputRTSemiAnnually$Dates = apply(InputRTSemiAnnually,1,function(x) { seq.Date( as.Date(x[['NextChildToBeSpawned']], origin="1970-01-01"), by='2 quarter', length.out = as.numeric(x['RemainingInstances'])) } )
library(lubridate)
InputRTMonthlysave = subset(InputRTMonthly, InputRTMonthly$RemainingInstances < 2)
InputRTMonthly = subset(InputRTMonthly, InputRTMonthly$RemainingInstances > 1)
for(i in 1:length(InputRTMonthly$Dates)){for(j in 2:length(InputRTMonthly$Dates[[i]])){ if(format(InputRTMonthly$Dates[[i]][j], "%m")  ==  format(InputRTMonthly$Dates[[i]][j-1], "%m")){InputRTMonthly$Dates[[i]][j-1] = as.Date(ceiling_date(InputRTMonthly$Dates[[i]][j-1] - 5, "month") -1) }  }}
library(dplyr)
InputRT = bind_rows(InputRTAnnually, InputRTBiWeekly, InputRTMonthly, InputRTQuarterly, InputRTSemiAnnually, InputRTWeekly, InputRTMonthlysave)
InputRT = subset(InputRT, InputRT$NextChildToBeSpawned > as.Date("2019-03-14"))
for(i in 1:length(InputRT$Dates)){
InputRT$NextScheduleDate[i] = InputRT$Dates[[i]][1]
}
InputOT = read.table("Deconv_Transfers.txt",  fill = TRUE, quote="", sep="\t", header = T, fileEncoding = "UCS-2LE")
InputOT$DueDate = as.Date(InputOT$DueDate, format = "%m/%d/%Y")
InputOT = subset(InputOT, InputOT$Status == 'WILLPROCESSON')
InputOT = subset(InputOT, InputOT$DueDate > '2019-03-18')
for(i in 1:(length(InputUsers$UserID)-1)){ if(InputUsers$UserID[i] == InputUsers$UserID[i+1]){
  InputUsers = InputUsers[-c(i+1),] 
}
}
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
InputAlertsLink = read.table("Deconv_AlertSubAccounts.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE")
InputAlerts = subset(InputAlerts, InputAlerts$AlertTitle == 'Available Balance is Below $__' | InputAlerts$AlertTitle == 'Daily or Weekly Available Balance' | InputAlerts$AlertTitle == 'Available Balance Equals or Exceeds $')
InputAlerts = merge(InputAlerts, InputAlertsLink, by = "AlertSubscriptionID")
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
OutputAccounts = read.csv("MWAAccountsOutput.csv", fill = TRUE, quote="\"", header = T, fileEncoding = "UTF-8-BOM", colClasses = c('character','factor' , 'factor', 'factor', 'factor', 'factor', 'factor', 'character', 'character', 'character', 'character', 'character', 'character', 'character', 'factor', 'character', 'character', 'character', 'character', 'character', 'factor', 'character', 'factor'))
InputAcct = read.table("Deconv_AccountData.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE", colClasses = c('character','factor' , 'factor', 'character', 'character', 'factor', 'factor', 'factor', 'character', 'character'))
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
OutputTransfers = read.csv("MWATransfersOutput.csv", fill = TRUE, quote="\"", header = T, fileEncoding = "UTF-8-BOM")
testing = merge(InputAcct, OutputAccounts, by.x = c("AccountNumber"), by.y = c("AccountNumber"))
testing2 = select(testing, AccountNumber, AccountID, UserId, CIF)
colnames(testing2)[1] = "AccountNumber"
colnames(testing2)[2] = "AccountID"
colnames(testing2)[3] = "UserId"
colnames(testing2)[4] = "CIF"
temp <- data.frame(do.call('rbind', strsplit(as.character(OutputTransfers$TransferString),'"',fixed=TRUE)))
colnames(temp)[4] = "StartDate"
colnames(temp)[7] = "Frequency"
colnames(temp)[9] = "DoUntil"
colnames(temp)[11] = "RemainingTimes"
colnames(temp)[14] = "NextScheduleDate"
temp$Frequency = as.numeric(sub(".*: *(.*?) *,.*", "\\1", temp$Frequency))
temp$DoUntil = as.numeric(sub(".*: *(.*?) *,.*", "\\1", temp$DoUntil))
temp$RemainingTimes = as.numeric(sub(".*: *(.*?) *,.*", "\\1", temp$RemainingTimes))
temp$NextScheduleDate = as.Date(temp$NextScheduleDate)
temp$StartDate = as.Date(temp$StartDate)
OutputTransfers$Frequency = temp$Frequency
OutputTransfers$DoUntil = temp$DoUntil
OutputTransfers$RemainingTimes = temp$RemainingTimes
OutputTransfers$NextScheduleDate = temp$NextScheduleDate
OutputTransfers$StartDate = temp$StartDate
temp <- data.frame(do.call('rbind', strsplit(as.character(OutputTransfers$ParameterValuesString),'"',fixed=TRUE)))
colnames(temp)[10] = "FromAccount"
colnames(temp)[14] = "FromType"
colnames(temp)[19] = "FromRouting"
colnames(temp)[22] = "ToAccount"
colnames(temp)[26] = "ToType"
colnames(temp)[29] = "ToRouting"
colnames(temp)[31] = "Amount"
colnames(temp)[68] = "CIF"
temp$FromRouting = as.numeric(sub(".*: *(.*?) *,.*", "\\1", temp$FromRouting))
temp$ToRouting = as.numeric(sub(".*: *(.*?) *,.*", "\\1", temp$ToRouting))
temp$Amount = as.numeric(sub(".*: *(.*?) *,.*", "\\1", temp$Amount))
OutputTransfers$FromAccount = temp$FromAccount
OutputTransfers$FromType = temp$FromType
OutputTransfers$FromRouting = temp$FromRouting
OutputTransfers$ToAccount = temp$ToAccount
OutputTransfers$ToType = temp$ToType
OutputTransfers$ToRouting = temp$ToRouting
OutputTransfers$Amount = temp$Amount
OutputTransfers$CIF = temp$CIF
OutputOT = subset(OutputTransfers, OutputTransfers$FrequencyId == 1)
OutputRT = subset(OutputTransfers, OutputTransfers$FrequencyId != 1)
unique(InputRT$Frequency)
OutputRT$FrequencyName = "Annually"
for(i in 1:length(OutputRT$FrequencyId)){if(OutputRT$FrequencyId[i] == 4){
  OutputRT$FrequencyName[i] = "Monthly"
}
  if(OutputRT$FrequencyId[i] == 6){
  OutputRT$FrequencyName[i] = "Quarterly"
  }
  if(OutputRT$FrequencyId[i] == 7){
  OutputRT$FrequencyName[i] = "Semi-Annually"
  }
  if(OutputRT$FrequencyId[i] == 3){
  OutputRT$FrequencyName[i] = "Weekly"
  }
 if(OutputRT$FrequencyId[i] == 5){
  OutputRT$FrequencyName[i] = "BiWeekly"
  }
}
IOT = merge(InputOT, testing2, by.x = c("FromAccountID"), by.y = c("AccountID") )
IOT = merge(IOT, testing2, by.x = c("ToAccountID"), by.y = c("AccountID"))
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
OutputUsers = read.csv("MWAUsersOutput.csv", fill = TRUE, quote="\"", header = T, fileEncoding = "UTF-8-BOM")
OutputOT = merge(OutputUsers, OutputOT, by.x = c("Id"), by.y = c("UserId"))
testing = merge(IOT, OutputOT, by.x = c("CIF.x","DueDate"), by.y = c("CIF","NextScheduleDate"))
a = unique(select(testing, DueDate, AccountNumber.x, AccountNumber.y)  )
testing = merge(IOT, OutputOT, by.x = c("CIF.x","DueDate"), by.y = c("CIF","NextScheduleDate"), all.x = T)
testing = subset(testing, is.na(testing$FirstName))
testing = subset(testing, testing$CIF.x == testing$CIF.y)
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
write.csv(testing, "OneX.csv")
```


```{r}
RTOT = merge(InputRT, testing2, by.x = c("FromAccountID"), by.y = c("AccountID") )
RTOT = merge(RTOT, testing2, by.x = c("ToAccountID"), by.y = c("AccountID"))
OutputRT = merge(OutputUsers, OutputRT, by.x = c("Id"), by.y = c("UserId"))
testing = merge(RTOT, OutputRT, by.x = c("CIF.x","NextChildToBeSpawned"), by.y = c("CIF","NextScheduleDate"), all.x = T)
testing = subset(testing, testing$NextChildToBeSpawned > "2019-03-18")
RT = subset(testing, is.na(testing$FirstName))
RT$Dates = NULL
RT = subset(RT, RT$CIF.x == RT$CIF.y)
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
write.csv(RT, "Recurringx.csv")
```

```{r}
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
Recurring = read.csv("Recurring.csv", fill = TRUE, quote="\"", header = T, fileEncoding = "UTF-8-BOM")
Recurring$Same = 1
for(i in 1:length(Recurring$AccountNumber.x)){if(as.character(Recurring$CIF.x[i]) != as.character(Recurring$CIF.y[i])){
  Recurring$Same[i] = 0
}}
RT = subset(Recurring, Recurring$Same == 1)
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
write.csv(RT, "Recurring2.csv")
```

```{r}
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
InputNicknames = read.table("Deconv_AccountNicknameData.txt",  fill = TRUE, quote="\"", sep="\t", header = T, fileEncoding = "UCS-2LE") 
a  = merge(InputNicknames, InputAcct, by = "AccountID")  
testing  = merge(a, testing2, by = "AccountID") 
length(unique(OutputNicknames$AccountNumber))
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
OutputNicknames = read.csv("Nicknames.csv", fill = TRUE, quote="\"", header = T, fileEncoding = "UTF-8-BOM")
a = merge(testing, OutputNicknames, by.x = c("AccountNumber.x"), by.y = c("AccountNumber"), all.x = T)
b = subset(a, is.na(a$Nickname))
length(unique(b$AccountID))
setwd("X:/Office of the CEO/Project/Analysts/Reid Hulsizer/MWA Input Files/Modified Files for Testing")
write.csv(b, "NicknamesIssue2.csv")
```





